apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u2d2x3vms-python 
  janus-idp.io/tekton: u2d2x3vms-python
  backstage.io/kubernetes-id: u2d2x3vms-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u2d2x3vms-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml